### ISSUE TITLE
how to use the tfnet model to generate test audio.

### ISSUE THREAD

**Issue by LXP-Never** [moodoki/tfnet#1]
Hi moodoki,
    Thank you for the open source code，I found that the SNR obtained using tensorflow is different from the SNR obtained by the numpy method
```
def snr(x, y):
    l2 = tf.reduce_mean((x-y)**2 + 1e-6, axis=[1, 2]) #pylint: disable=invalid-name
    l2_norm = tf.reduce_mean(y**2, axis=[1, 2])
    _snr = 10 * tf.log(l2_norm / l2 + 1e-8) / tf.log(10.)

    return _snr
```

1e-6 will have an impact on the final result, and numpy method of calculating SNR is correct

```
def compute_snr(labels, logits):
    sqrt_l2_loss = np.mean((logits - labels) ** 2)
    sqrn_l2_norm = np.mean(labels ** 2)
    snr = 10 * np.log(sqrn_l2_norm / sqrt_l2_loss + 1e-8) / np.log(10.)
    # avg_snr = np.mean(snr, axis=0)
    return snr
```

**Comment by moodoki** [comment]
Thanks for pointing this out. Yes, it affects the computed SNR slightly, however, it's necessary to avoid NaNs in some cases.

The `+ 1e-8` was also added for the same intention. This, however, has no effect as TensorFlow works in float32 and the smallest number float32 can represent is 1e-7. (The can be checked in Tensorflow >2.0 with `tf.keras.backend.epsilon()`).

The code in NumPy will work as NumPy uses float64 by default.

**Comment by LXP-Never** [comment]
Oh, thank you for pointing it out, I didn’t even think that the smallest number float32 can represent is 1e-7
