### ISSUE TITLE
how to generator audio

### ISSUE THREAD

**Issue by LXP-Never** [moodoki/tfnet#2]
hi 
I want to generate super-resolution audio for each narrowband speech file
But it can only generate frames (8192, 1)
How to generate the entire audio file instead of every frame？
thank

**Comment by moodoki** [comment]
In our experiments, we simply split audio files into 8192-length segments and then concatenate the output.

**Comment by LXP-Never** [comment]
Direct concatenate will cause the loss of spectrum between frames

**Comment by LXP-Never** [comment]
> 在我们的实验中，我们仅将音频文件分割为8192个长度的片段，然后将输出连接起来。

thank you for your reply，but, direct concatenate will cause the loss of spectrum between frames，

**Comment by moodoki** [comment]
Yes, it may not be ideal. You can also try overlapping windows but we have not tried that. The samples that we've provided on our website were generated simply by concatenating.
